#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jul 24 23:41:50 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}