#!groovy

// Generated by IBM TransformationAdvisor
// Tue Aug 06 04:58:10 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}