#!groovy

// Generated by IBM TransformationAdvisor
// Mon Aug 05 02:46:20 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = 'clean package'
    test='false'
}